const ADDAX_PETROLEUM = 'ADDAX PETROLEUM';
const PERENCO = 'PERENCO(TAM)';
const GUINNESS = 'GUINNESS VL';
const COTCO = 'COTCO';
const CIMENCAM = 'CIMENCAM';
const RAZEL_TRUCKS = 'RAZEL TRUCKS';
const KPDC = 'KPDC KRIBI';
const RAZEL_CAMEROUN = 'RAZEL CAMEROUN';
const RAZEL_PL = 'RAZEL TRUCKS(SAV CAMTRACK)';
const RAZEL_VL = 'RAZEL VL(SAV CAMTRACK)';
const DKT = 'DKT INTERNATIONAL';
const DKT_CAMEROUN = 'DKT CAMEROUN';
const ALIOS = 'LOCATAIRES ALIOS';
const ALL_VEHICLE = 'All Vehicle';
const LX_45 = 'LX 45';
const TOTAL_CAMEROON = 'CAMEROUN';
const CAMEROUN_RANKING_REPORT = 'CAMEROUN_RANKING_REPORT';
const CAMEROUN_NIGHT_DRIVING_REPORT = 'CAMEROUN_NIGHT_DRIVING_REPORT';
const CAMEROUN_REPOS_HEBDOMADAIRE = 'CAMEROUN_REPOS_HEBDOMADAIRE';
const CAMEROUN_CLOTURE_ACTIVITE = 'CAMEROUN_CLOTURE_ACTIVITE'

module.exports = {
  ADDAX_PETROLEUM,
  PERENCO,
  GUINNESS,
  COTCO,
  CIMENCAM,
  RAZEL_TRUCKS,
  KPDC,
  RAZEL_CAMEROUN,
  RAZEL_PL,
  RAZEL_VL,
  DKT,
  DKT_CAMEROUN,
  ALIOS,
  ALL_VEHICLE,
  LX_45,
  TOTAL_CAMEROON,
  CAMEROUN_RANKING_REPORT,
  CAMEROUN_NIGHT_DRIVING_REPORT,
  CAMEROUN_REPOS_HEBDOMADAIRE,
  CAMEROUN_CLOTURE_ACTIVITE
};
