const ADDAX_PETROLEUM = "ADDAX PETROLEUM";
const PERENCO = "PERENCO(TAM)";
const GUINNESS = "GUINNESS VL";
const COTCO = "COTCO";
const CIMENCAM = "CIMENCAM";
const RAZEL_VL = "RAZEL VL";
const RAZEL_TRUCKS = "RAZEL TRUCKS";

module.exports = {
  ADDAX_PETROLEUM,
  PERENCO,
  GUINNESS,
  COTCO,
  CIMENCAM,
  RAZEL_VL,
  RAZEL_TRUCKS,
};
