const ADDAX_PETROLEUM = 'ADDAX PETROLEUM';
const PERENCO = 'PERENCO(TAM)';
const GUINNESS = 'GUINNESS VL';
const COTCO = 'COTCO';
const CIMENCAM = 'CIMENCAM';
const RAZEL_TRUCKS = 'RAZEL TRUCKS';
const KPDC = 'KPDC KRIBI';
const RAZEL_CAMEROUN = 'RAZEL CAMEROUN';
const RAZEL_PL = 'RAZEL TRUCKS(SAV CAMTRACK)';
const RAZEL_VL = 'RAZEL VL(SAV CAMTRACK)';
const DKT = 'DKT INTERNATIONAL';
const DKT_CAMEROUN = 'DKT CAMEROUN';
const ALIOS = 'LOCATAIRES ALIOS';
const ALL_VEHICLE = 'All Vehicle'

module.exports = {
  ADDAX_PETROLEUM,
  PERENCO,
  GUINNESS,
  COTCO,
  CIMENCAM,
  RAZEL_TRUCKS,
  KPDC,
  RAZEL_CAMEROUN,
  RAZEL_PL,
  RAZEL_VL,
  DKT,
  DKT_CAMEROUN,
  ALIOS,
  ALL_VEHICLE
};
