const ADMIN_ADDAX = 'admin ADDAX';
const ADMIN_PERENCO = 'Admin PERENCO';
const ADMIN_SABC = 'admin SABC';
const ADMIN_GLOBELEQ = 'admin GLOBELEQ';
const ADMIN_RAZEL = 'ADMIN RAZEL-BELLOY JULIEN';

module.exports = {
  ADMIN_ADDAX,
  ADMIN_PERENCO,
  ADMIN_SABC,
  ADMIN_RAZEL,
  ADMIN_GLOBELEQ,
};
