//globals subgroups
const SYNTHESE = "SYNTHESE"
const EXCES_DE_VITESSE="Excès de Vitesse"


//Addax
const EXCEPTIONS = "EXCEPTIONS"
const ACTIVITY_CARS = "ACTIVITY CARS"
const SOMMAIRE = "SOMMAIRE"
const NOT_AT_PARKED = "Not at Parked"
const EXCESSIVE_IDLE ="Excessive Idle"
const ECO_CONDUITE="Éco-conduite"


//perenco
const ECO_DRIVING="Eco driving"
const DETAIL_TRAJET="Détail trajet"
const CONDUITE_DE_NUIT="Conduite de NUIT"
const SPEEDING ="Speeding Detail"
const EXCES_DE_VITESSE_NAT3="Excès de Vitesse Nat3"
const EXCES_DE_VITESSE_VILLE="Excès de Vitesse Ville"
const EXCES_DE_VITESSE_BASE_PERENCO="Excès de Vitesse BASE PERENCO"
const EXCES_DE_VITESSE_HORS_VILLE="Excès de Vitesse HORS VILLE"
const SPEEDING_DETAIL = "Speeding Détail"
const DASHBORD_SPEEDING="DASHBORD EXCES DE VITESSE PERENCO"
const EXCES_DE_VITESSE_LEGERE_VILLE  ="Excès de vitesse Légère ville"
const EXCES_DE_VITESSE_LEGERE_HORS_VILLE  ="Excès de vitesse Légère Hors ville"
const EXCES_DE_VITESSE_SEVERE_VILLE  ="Excès de vitesse Sévère ville"
const EXCES_DE_VITESSE_SEVERE_HORS_VILLE  ="Excès de vitesse Sévère Hors ville"
const EXCES_DE_VITESSE_LEGERE_NAT3_VILLE  ="Excès de vitesse  Légère Nat3"
const EXCES_DE_VITESSE_SEVERE_NAT3_VILLE  ="Excès de vitesse  Sévère Nat3"
const EXCES_DE_VITESSE_BASE_WOURI ="Excès de vitesse Base WOURI"
const EXCES_DE_VITESSE_PISTE_BIPAGA ="Excès de vitesse Piste BIPAGA"
const ZONES="Zones"
const TRACKING_TRACAFIC="TRACKING_TRACAFIC"
const RAPPORT_GUINNESS="RAPPORT GUINNESS"

//cotco
const RAPPORT_COTCO="rapport cotco"

//cimencam
const RAPPORT_CIMENCAM="rapport cimencam"


module.exports = {
    SYNTHESE,
    EXCEPTIONS,
    ACTIVITY_CARS,
    SOMMAIRE,
    NOT_AT_PARKED,
    EXCESSIVE_IDLE,
    ECO_CONDUITE,
    EXCES_DE_VITESSE,
    ECO_DRIVING,
    DETAIL_TRAJET,
    CONDUITE_DE_NUIT,
    SPEEDING,
    ZONES,
    EXCES_DE_VITESSE_BASE_PERENCO,
    EXCES_DE_VITESSE_HORS_VILLE,
    EXCES_DE_VITESSE_NAT3,
    EXCES_DE_VITESSE_VILLE,
    SPEEDING_DETAIL,
    EXCES_DE_VITESSE_LEGERE_VILLE,
    EXCES_DE_VITESSE_SEVERE_VILLE,
    EXCES_DE_VITESSE_LEGERE_HORS_VILLE,
    EXCES_DE_VITESSE_SEVERE_HORS_VILLE,
    EXCES_DE_VITESSE_LEGERE_NAT3_VILLE,
    EXCES_DE_VITESSE_SEVERE_NAT3_VILLE,
    EXCES_DE_VITESSE_BASE_WOURI,
    EXCES_DE_VITESSE_PISTE_BIPAGA,
    TRACKING_TRACAFIC,
    RAPPORT_GUINNESS,
    RAPPORT_COTCO,
    RAPPORT_CIMENCAM,
    DASHBORD_SPEEDING
}