const SYNTHESE = "SYNTHESE"
const EXCEPTIONS = "EXCEPTIONS"
const ACTIVITY_CARS = "ACTIVITY CARS"
const SOMMAIRE = "SOMMAIRE"
const NOT_AT_PARKED = "Not at Parked"
const EXCESSIVE_IDLE ="Excessive Idle"
const ECO_CONDUITE="Éco-conduite"
const EXCES_DE_VITESSE="Excès de Vitesse"



module.exports = {SYNTHESE, EXCEPTIONS, ACTIVITY_CARS,SOMMAIRE, NOT_AT_PARKED, EXCESSIVE_IDLE, ECO_CONDUITE, EXCES_DE_VITESSE }