//globals subgroups
const SYNTHESE = 'SYNTHESE';
const EXCES_DE_VITESSE = 'Excès de Vitesse';

//Addax
const EXCEPTIONS = 'EXCEPTIONS';
const ACTIVITY_CARS = 'ACTIVITY CARS';
const SOMMAIRE = 'SOMMAIRE';
const NOT_AT_PARKED = 'Not at Parked';
const EXCESSIVE_IDLE = 'Excessive Idle';
const ECO_CONDUITE = 'Éco-conduite';

//perenco
const ECO_DRIVING = 'Eco driving';
const DETAIL_TRAJET = 'Détail trajet';
const CONDUITE_DE_NUIT = 'Conduite de NUIT';
const SPEEDING = 'Speeding Detail';
const EXCES_DE_VITESSE_NAT3 = 'Excès de Vitesse Nat3';
const EXCES_DE_VITESSE_VILLE = 'Excès de Vitesse Ville';
const EXCES_DE_VITESSE_BASE_PERENCO = 'Excès de Vitesse BASE PERENCO';
const EXCES_DE_VITESSE_HORS_VILLE = 'Excès de Vitesse HORS VILLE';
const SPEEDING_DETAIL = 'Speeding Détail';
const DASHBORD_SPEEDING = 'DASHBORD EXCES DE VITESSE PERENCO';
const EXCES_DE_VITESSE_LEGERE_VILLE = 'Excès de vitesse Légère ville';
const EXCES_DE_VITESSE_LEGERE_HORS_VILLE = 'Excès de vitesse Légère Hors ville';
const EXCES_DE_VITESSE_SEVERE_VILLE = 'Excès de vitesse Sévère ville';
const EXCES_DE_VITESSE_SEVERE_HORS_VILLE = 'Excès de vitesse Sévère Hors ville';
const EXCES_DE_VITESSE_LEGERE_NAT3_VILLE = 'Excès de vitesse  Légère Nat3';
const EXCES_DE_VITESSE_SEVERE_NAT3_VILLE = 'Excès de vitesse  Sévère Nat3';
const EXCES_DE_VITESSE_BASE_WOURI = 'Excès de vitesse Base WOURI';
const EXCES_DE_VITESSE_PISTE_BIPAGA = 'Excès de vitesse Piste BIPAGA';
const ZONES = 'Zones';
const TRACKING_TRACAFIC = 'TRACKING_TRACAFIC';
const RAPPORT_GUINNESS = 'RAPPORT GUINNESS';

//cotco
const RAPPORT_COTCO = 'rapport cotco';

//cimencam
const RAPPORT_CIMENCAM = 'rapport cimencam';

//kPDC
const TRAJET_FLOTTE_KPDC = 'Trajets Flotte';
const EXCES_VITESSE_FLOTTE_KPDC = 'Excès de Vitesse';
const HARSH_BRAKING = 'HARSH BRAKING';
const CONTACT_ON = 'Contact On';
const CONTACT_OFF = 'Contact Off';
const DASHBORD = 'Dashboard';
const ARRET_MOTEUR = 'Arret moteur en marche';

//Razel
const CONDUITE_DE_NUIT_RAZEL_GROUP = 'CONDUITE DE NUIT';
const DETAIL_TRAJET_FLOTTE_GROUP = 'DETAIL TRAJET FLOTTE';
const CONDUITE_DE_WEEKEND_RAZEL_GROUP =
  'CONDUITE DE WEEKEND RAZEL (SAMEDI & DIMANCHE)';
const ECO_DRIVING_RAZEL_GROUP = 'Eco driving';
const EXCES_DE_VITESSE_AG_PL_GROUP =
  'EXCES DE VITESSE AGGLOMERATION PL (30KM/H)';
const EXCES_DE_VITESSE_AG_VL_GROUP =
  'EXCES DE VITESSE AGGLOMERATION VL (60KM/H)';
const EXCES_DE_VITESSE_HA_PL_GROUP =
  'EXCES DE VITESSE HORS AGGLOMERATION PL (60KM/H)';
const EXCES_DE_VITESSE_HA_VL_GROUP =
  'EXCES DE VITESSE HORS AGGLOMERATION VL (90KM/H)';
const RALENTI_MOTEUR_RAZEL_GROUP = 'RALENTI MOTEUR';
const RAPPORT_SYNTHESE_ACTIVITE_RAZEL_GROUP =
  'RAPPORT SYNSTHESE ACTIVITE RAZEL';
const DETAIL_FLOTTE_PRODUCTIVITE = 'Trajet flotte+Productivité';
const DETAIL_FLOTTE_PRODUCTIVITE_TITLE_VL =
  'Résumé Activité flotte + Productivité VL';
const DETAIL_FLOTTE_PRODUCTIVITE_TITLE_PL =
  'Résumé Activité flotte + Productivité PL';

//DKT
const SYNTHESE_DKT = 'Synthèse activité';
const STATIONNEMENT_ON = 'Stationnement On';
const ECO_DRIVING_DKT = 'Eco driving';
const CONDUITE_DE_NUIT_DKT = 'Conduite de nuit';
const EXCES_DE_VITESSE_DKT = 'Excès de vitesse';
const DETAIL_TRAJET_VEHICULE_DKT = 'Detail trajet véhicule';
const CONDUITE_WEEKEND_DKT = 'Conduite du weekend';

// ALIOS
const LIST_VEHICULES_GROUP = 'Liste des Vehicules';


//total
STATUS = 'Status(cropped)';
TRIP_END = "Trip end";
TRIP = "Trip"

module.exports = {
  SYNTHESE,
  EXCEPTIONS,
  ACTIVITY_CARS,
  SOMMAIRE,
  NOT_AT_PARKED,
  EXCESSIVE_IDLE,
  ECO_CONDUITE,
  EXCES_DE_VITESSE,
  ECO_DRIVING,
  DETAIL_TRAJET,
  CONDUITE_DE_NUIT,
  SPEEDING,
  ZONES,
  EXCES_DE_VITESSE_BASE_PERENCO,
  EXCES_DE_VITESSE_HORS_VILLE,
  EXCES_DE_VITESSE_NAT3,
  EXCES_DE_VITESSE_VILLE,
  SPEEDING_DETAIL,
  EXCES_DE_VITESSE_LEGERE_VILLE,
  EXCES_DE_VITESSE_SEVERE_VILLE,
  EXCES_DE_VITESSE_LEGERE_HORS_VILLE,
  EXCES_DE_VITESSE_SEVERE_HORS_VILLE,
  EXCES_DE_VITESSE_LEGERE_NAT3_VILLE,
  EXCES_DE_VITESSE_SEVERE_NAT3_VILLE,
  EXCES_DE_VITESSE_BASE_WOURI,
  EXCES_DE_VITESSE_PISTE_BIPAGA,
  TRACKING_TRACAFIC,
  RAPPORT_GUINNESS,
  RAPPORT_COTCO,
  RAPPORT_CIMENCAM,
  DASHBORD_SPEEDING,
  TRAJET_FLOTTE_KPDC,
  EXCES_VITESSE_FLOTTE_KPDC,
  HARSH_BRAKING,
  CONTACT_ON,
  CONTACT_OFF,
  ARRET_MOTEUR,
  DASHBORD,

  CONDUITE_DE_NUIT_RAZEL_GROUP,
  CONDUITE_DE_WEEKEND_RAZEL_GROUP,
  ECO_DRIVING_RAZEL_GROUP,
  EXCES_DE_VITESSE_AG_PL_GROUP,
  EXCES_DE_VITESSE_AG_VL_GROUP,
  RALENTI_MOTEUR_RAZEL_GROUP,
  RAPPORT_SYNTHESE_ACTIVITE_RAZEL_GROUP,
  EXCES_DE_VITESSE_HA_VL_GROUP,
  EXCES_DE_VITESSE_HA_PL_GROUP,
  DETAIL_TRAJET_FLOTTE_GROUP,
  DETAIL_FLOTTE_PRODUCTIVITE,
  DETAIL_FLOTTE_PRODUCTIVITE_TITLE_VL,
  DETAIL_FLOTTE_PRODUCTIVITE_TITLE_PL,

  SYNTHESE_DKT,
  STATIONNEMENT_ON,
  ECO_DRIVING_DKT,
  CONDUITE_DE_NUIT_DKT,
  EXCES_DE_VITESSE_DKT,
  DETAIL_TRAJET_VEHICULE_DKT,
  CONDUITE_WEEKEND_DKT,

  LIST_VEHICULES_GROUP,
  STATUS,
  TRIP_END,
  TRIP
};
