//Addax
const ACTIVITY_REPORT_OF_ADDAX_PETROLEUM = 'ACTIVITY-REPORT-OF-ADDAX-PETROLEUM';
const EXCEPTION_REPORT_VEHICULES_ADDAX_PETROLEUM =
  'EXCEPTION-REPORT-VEHICULES-ADDAX-PETROLEUM';
const LIST_OF_VEHICLES_NOT_AT_ADDAX_PARKING =
  'LIST-OF-VEHICLES-NOT AT-ADDAX-PARKING';

//perenco
const RAPPORT_ACTIVITE_FLOTTE_PERENCO = 'Rapport activité flotte PERENCO';
const RAPPORT_EXCES_DE_VITESSE_FLOTTE = 'Rapport Excès de Vitesse PERENCO';
const RAPPORT_TRAVERSE_ZONE_BONABERI =
  'Rapport fonction ayant traversé la zone de BONABERI';

//guinness
const RAPPORT_JOURNALIER_GUINESS = 'RAPPORT JOURNALIER  GUINNESS';
const RAPPORT_MENSUEL_GUINESS = 'RAPPORT MENSUEL  GUINNESS';

//cotco
const RAPPORT_JOURNALIER_COTCO = 'RAPPORT JOURNALIER COTCO';

//cimencam
const RAPPORT_JOURNALIER_CIMENCAM = 'RAPPORT JOURNALIER CIMENCAM(GEOFENCE)';

//KPDC
const DETAIL_TRAJET_FLOTTE = 'Détail Trajets Flotte';
const EXCES_DE_VITESSE_FLOTTE = 'Excès de Vitesse Flotte';
const RAPPORT_GLOBELEQ_NOUVEAU_MODULE_KPDC =
  'RAPPORT GLOBELEQ NOUVEAU MODULE KPDC';
const STATIONNEMENT_ON_OFF = 'Stationnement ON/OFF';

module.exports = {
  ACTIVITY_REPORT_OF_ADDAX_PETROLEUM,
  EXCEPTION_REPORT_VEHICULES_ADDAX_PETROLEUM,
  LIST_OF_VEHICLES_NOT_AT_ADDAX_PARKING,
  RAPPORT_ACTIVITE_FLOTTE_PERENCO,
  RAPPORT_EXCES_DE_VITESSE_FLOTTE,
  RAPPORT_TRAVERSE_ZONE_BONABERI,
  RAPPORT_JOURNALIER_GUINESS,
  RAPPORT_MENSUEL_GUINESS,
  RAPPORT_JOURNALIER_COTCO,
  RAPPORT_JOURNALIER_CIMENCAM,
  DETAIL_TRAJET_FLOTTE,
  EXCES_DE_VITESSE_FLOTTE,
  RAPPORT_GLOBELEQ_NOUVEAU_MODULE_KPDC,
  STATIONNEMENT_ON_OFF,
};
