//vehicle groups
const ALL_VEHICLES ='All vehicles'


//places or geofences
const USINE_BONABERIE="100001_USINE BONABERI"
const USINE_MORTIER = "100010_Usine Mortier"
const GAR_BESSENGUE ="100019_DEPOT GARE BESSENGUE"
const USINE_NOMAYOS ="100003_USINE DE NOMAYOS"
const PORT_KRIBI = "100025_USINE KRIBI"
const USINE_FIGUIL ="100002_USINE FIGUIL"
const CARRIERE_BIDZA="100027_CARRIERE DE BIDZAR"
const CARRIERE_SABLE ="100029_CARRIERE DE SABLE"
const CARRIERE_ARGIL ="100028_CARRIERE ARGILE"
const CARRIERE_FOUMBOT="100024_CARRIERE DE FOUMBOT"

module.exports={ALL_VEHICLES,USINE_BONABERIE,USINE_MORTIER,GAR_BESSENGUE,USINE_NOMAYOS,PORT_KRIBI,USINE_FIGUIL,CARRIERE_BIDZA,CARRIERE_SABLE,CARRIERE_ARGIL,CARRIERE_FOUMBOT}