//vehicle groups
const ALL_VEHICLES ='All vehicles'


//places or geofences
const USINE_BONABERIE="100001_USINE BONABERI"
const USINE_MORTIER = "Usine Mortier Douala"
const GAR_BESSENGUE ="Gare de Bessengue"
const USINE_NOMAYOS ="100003_USINE DE NOMAYOS"
const PORT_KRIBI = "USINE KRIBI"
const USINE_FIGUIL ="100002_USINE FIGUIL"
const CARRIERE_BIDZA="Carrière de Bidzar"
const CARRIERE_SABLE ="Carrière de Sable"
const CARRIERE_ARGIL ="Carrière d'Argile"
const CARRIERE_FOUMBOT="100024_CARRIERE CIMENCAM FOUMBOT"


module.exports={ALL_VEHICLES,USINE_BONABERIE,USINE_MORTIER,GAR_BESSENGUE,USINE_NOMAYOS,PORT_KRIBI,USINE_FIGUIL,CARRIERE_BIDZA,CARRIERE_SABLE,CARRIERE_ARGIL,CARRIERE_FOUMBOT}